name: Ruby

on: [push,pull_request]

jobs:
  versions:
    name: Get versions
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: |
          jq -h
          git clone https://github.com/sstephenson/ruby-build.git
          cd ruby-build
          ./install.sh
          ruby-build --version
          echo '::set-output name=matrix::["2.6", "2.7"]'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  build:
    needs: versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: ${{ fromJson(needs.versions.outputs.matrix) }}
    name: Ruby ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: |
        bundle exec rake
