name: Ruby

on: [push,pull_request]

jobs:
  versions:
    name: Get versions
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        name: Set Matrix
        run: |
          versions=$(
            curl -s https://raw.githubusercontent.com/ruby/setup-ruby/master/ruby-builder-versions.json |
              jq -c '[.ruby[]
                | select(test("preview|rc|debug") | not)
                | if test("^[a-z]") then . else .[0:3] end
                | select(. >= "2.5")]
                | unique'
            )
          echo "::set-output name=matrix::${versions}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  build:
    needs: versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ${{ fromJson(needs.versions.outputs.matrix) }}
    name: Ruby ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: |
        bundle exec rake
